name: neubay
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - glew=2.1.0
  - glfw3=3.2.1
  - icu=73.1
  - ld_impl_linux-64=2.40
  - libdrm=2.4.124
  - libegl=1.7.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgl=1.7.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libllvm15=15.0.7
  - libpciaccess=0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - mesalib=25.1.1
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - spirv-tools=2025.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.3.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - asttokens==3.0.0
    - attrs==25.3.0
    - black==25.1.0
    - certifi==2025.4.26
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - chex==0.1.89
    - click==8.2.1
    - cloudpickle==3.1.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - cython==0.29.37
    - d4rl==1.1
    - decorator==5.2.1
    - distrax==0.1.5
    - dm-control==1.0.20
    - dm-env==1.6
    - dm-tree==0.1.9
    - equinox==0.12.2
    - etils==1.12.2
    - exceptiongroup==1.3.0
    - executing==2.2.0
    - farama-notifications==0.0.4
    - fasteners==0.19
    - fonttools==4.58.2
    - fsspec==2025.5.1
    - gast==0.6.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - glfw==2.9.0
    - gym==0.23.1
    - gym-notices==0.0.8
    - h5py==3.14.0
    - hydra-core==1.3.2
    - idna==3.10
    - imageio==2.37.0
    - importlib-resources==6.5.2
    - ipdb==0.13.13
    - ipython==8.37.0
    - jax==0.5.3
    - jax-cuda12-pjrt==0.5.3
    - jax-cuda12-plugin==0.5.3
    - jaxlib==0.5.3
    - jaxtyping==0.3.2
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.1
    - kiwisolver==1.4.8
    - labmaze==1.0.6
    - lxml==5.4.0
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - matplotlib-inline==0.1.7
    - mjrl==1.0.0
    - ml-dtypes==0.5.1
    - mujoco==3.1.6
    - mujoco-py==2.1.2.14
    - mypy-extensions==1.1.0
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvcc-cu12==12.8.93
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvshmem-cu12==3.2.5
    - nvidia-nvtx-cu12==12.6.77
    - omegaconf==2.3.0
    - opt-einsum==3.4.0
    - optax==0.2.5
    - packaging==25.0
    - pandas==2.3.0
    - parso==0.8.4
    - patchelf==0.17.2.2
    - pathspec==0.12.1
    - pettingzoo==1.25.0
    - pexpect==4.9.0
    - pillow==11.2.1
    - platformdirs==4.3.8
    - prompt-toolkit==3.0.51
    - protobuf==6.31.1
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pybullet==3.2.7
    - pycparser==2.22
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    - pygments==2.19.1
    - pyopengl==3.1.9
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - scikit-learn==1.7.0
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentry-sdk==2.29.1
    - setproctitle==1.3.6
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - tensorflow-probability==0.25.0
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - tomli==2.2.1
    - toolz==1.0.0
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.14.0
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - urllib3==2.4.0
    - wadler-lindig==0.1.6
    - wandb==0.20.1
    - wcwidth==0.2.13
    - wrapt==1.17.2
    - zipp==3.22.0